name: Node.js CI

on:
  schedule:
  - cron: "0 1/12 * * *"
  workflow_dispatch:

jobs:
  init:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: Run
        run: npm start
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: data.json
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Revalidate website
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://egdata.app/api/revalidate-top?secret=${{ secrets.SECRET_REVALIDATE }}'
          method: 'GET'
  
